// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreManager.Persistence;

#nullable disable

namespace StoreManager.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260114173038_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StoreManager.Domain.Chain.ChainEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<DateTime>("ModifiedOn")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_chain_entities");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("ix_chain_entities_created_on");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_chain_entities_name");

                    b.ToTable("chain_entities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ec199f0-4c26-4d20-bbdd-39ac844237b8"),
                            CreatedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            ModifiedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Name = "OptiView"
                        },
                        new
                        {
                            Id = new Guid("d3271c28-5e1d-4011-9f79-aa573a9f2e3c"),
                            CreatedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            ModifiedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Name = "FocalPoint"
                        },
                        new
                        {
                            Id = new Guid("e887f9ce-2096-4832-8587-f96d9c7d8bc7"),
                            CreatedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            ModifiedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Name = "FocusOptics"
                        },
                        new
                        {
                            Id = new Guid("7eaf61d2-6d20-4ef7-9e2c-3e230456ae3c"),
                            CreatedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            ModifiedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Name = "ClearSight"
                        });
                });

            modelBuilder.Entity("StoreManager.Domain.Store.StoreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("ChainId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chain_id");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ModifiedOn")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("pk_store_entities");

                    b.HasIndex("ChainId")
                        .HasDatabaseName("ix_store_entities_chain_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_store_entities_name");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_store_entities_number");

                    b.ToTable("store_entities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("82d72abf-0045-4aaa-9d8b-78f28b437052"),
                            ChainId = new Guid("5ec199f0-4c26-4d20-bbdd-39ac844237b8"),
                            CreatedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Email = "TestMail@OptiView.dk",
                            ModifiedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Name = "OptiView Downtown",
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("6c458b7e-c560-47c0-9e7c-5e66adf87192"),
                            ChainId = new Guid("5ec199f0-4c26-4d20-bbdd-39ac844237b8"),
                            CreatedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Email = "TestMail@OptiView.dk",
                            ModifiedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Name = "OptiView Downtown",
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("d84a8b08-7d18-4c23-a8ac-efc11c585d74"),
                            ChainId = new Guid("d3271c28-5e1d-4011-9f79-aa573a9f2e3c"),
                            CreatedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Email = "TestMail@OptiView.dk",
                            ModifiedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Name = "OptiView Downtown",
                            Number = 3
                        },
                        new
                        {
                            Id = new Guid("7d7e8194-b981-478a-baee-57982fa3f699"),
                            ChainId = new Guid("d3271c28-5e1d-4011-9f79-aa573a9f2e3c"),
                            CreatedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Email = "TestMail@OptiView.dk",
                            ModifiedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Name = "OptiView Downtown",
                            Number = 4
                        },
                        new
                        {
                            Id = new Guid("2ecacee5-f3c8-43e0-9ca6-379c49248afb"),
                            ChainId = new Guid("e887f9ce-2096-4832-8587-f96d9c7d8bc7"),
                            CreatedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Email = "TestMail@OptiView.dk",
                            ModifiedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Name = "OptiView Downtown",
                            Number = 5
                        },
                        new
                        {
                            Id = new Guid("2277a2ce-6623-4879-a3b5-709ba9fa625e"),
                            ChainId = new Guid("e887f9ce-2096-4832-8587-f96d9c7d8bc7"),
                            CreatedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Email = "TestMail@OptiView.dk",
                            ModifiedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Name = "OptiView Downtown",
                            Number = 6
                        },
                        new
                        {
                            Id = new Guid("4a15bcc2-9104-46e7-8a6c-b2030c1d573b"),
                            ChainId = new Guid("7eaf61d2-6d20-4ef7-9e2c-3e230456ae3c"),
                            CreatedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Email = "TestMail@OptiView.dk",
                            ModifiedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Name = "OptiView Downtown",
                            Number = 7
                        },
                        new
                        {
                            Id = new Guid("23273be7-91ad-4095-a891-f10f0633a420"),
                            ChainId = new Guid("7eaf61d2-6d20-4ef7-9e2c-3e230456ae3c"),
                            CreatedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Email = "TestMail@OptiView.dk",
                            ModifiedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Name = "OptiView Downtown",
                            Number = 8
                        },
                        new
                        {
                            Id = new Guid("1e8d0a09-b7b9-4a94-a293-cff36e767bea"),
                            CreatedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Email = "TestMail@OptiView.dk",
                            ModifiedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Name = "OptiView Downtown",
                            Number = 9
                        },
                        new
                        {
                            Id = new Guid("a2f309d9-e908-4ee1-9365-b72f7d088764"),
                            CreatedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Email = "TestMail@OptiView.dk",
                            ModifiedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Name = "OptiView Downtown",
                            Number = 10
                        },
                        new
                        {
                            Id = new Guid("e0aa46d0-3e3f-43e3-beb0-d71dfbc8500a"),
                            CreatedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Email = "TestMail@OptiView.dk",
                            ModifiedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Name = "OptiView Downtown",
                            Number = 11
                        },
                        new
                        {
                            Id = new Guid("ea911dd7-044d-45ff-b380-e04b5a8c1aa9"),
                            CreatedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Email = "TestMail@OptiView.dk",
                            ModifiedOn = new DateTime(2026, 12, 1, 16, 22, 44, 0, DateTimeKind.Unspecified),
                            Name = "OptiView Downtown",
                            Number = 12
                        });
                });

            modelBuilder.Entity("StoreManager.Domain.Store.StoreEntity", b =>
                {
                    b.HasOne("StoreManager.Domain.Chain.ChainEntity", "Chain")
                        .WithMany("Stores")
                        .HasForeignKey("ChainId")
                        .HasConstraintName("fk_store_entities_chain_entities_chain_id");

                    b.OwnsOne("StoreManager.Domain.Common.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("StoreEntityId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("address_city");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("address_street");

                            b1.HasKey("StoreEntityId");

                            b1.ToTable("store_entities");

                            b1.WithOwner()
                                .HasForeignKey("StoreEntityId")
                                .HasConstraintName("fk_store_entities_store_entities_id");

                            b1.HasData(
                                new
                                {
                                    StoreEntityId = new Guid("82d72abf-0045-4aaa-9d8b-78f28b437052"),
                                    City = "Aalborg",
                                    PostalCode = "9000",
                                    Street = "TestStreet 1"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("6c458b7e-c560-47c0-9e7c-5e66adf87192"),
                                    City = "Aalborg",
                                    PostalCode = "9000",
                                    Street = "TestStreet 1"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("d84a8b08-7d18-4c23-a8ac-efc11c585d74"),
                                    City = "Aalborg",
                                    PostalCode = "9000",
                                    Street = "TestStreet 1"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("7d7e8194-b981-478a-baee-57982fa3f699"),
                                    City = "Aalborg",
                                    PostalCode = "9000",
                                    Street = "TestStreet 1"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("2ecacee5-f3c8-43e0-9ca6-379c49248afb"),
                                    City = "Aalborg",
                                    PostalCode = "9000",
                                    Street = "TestStreet 1"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("2277a2ce-6623-4879-a3b5-709ba9fa625e"),
                                    City = "Aalborg",
                                    PostalCode = "9000",
                                    Street = "TestStreet 1"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("4a15bcc2-9104-46e7-8a6c-b2030c1d573b"),
                                    City = "Aalborg",
                                    PostalCode = "9000",
                                    Street = "TestStreet 1"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("23273be7-91ad-4095-a891-f10f0633a420"),
                                    City = "Aalborg",
                                    PostalCode = "9000",
                                    Street = "TestStreet 1"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("1e8d0a09-b7b9-4a94-a293-cff36e767bea"),
                                    City = "Aalborg",
                                    PostalCode = "9000",
                                    Street = "TestStreet 1"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("a2f309d9-e908-4ee1-9365-b72f7d088764"),
                                    City = "Aalborg",
                                    PostalCode = "9000",
                                    Street = "TestStreet 1"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("e0aa46d0-3e3f-43e3-beb0-d71dfbc8500a"),
                                    City = "Aalborg",
                                    PostalCode = "9000",
                                    Street = "TestStreet 1"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("ea911dd7-044d-45ff-b380-e04b5a8c1aa9"),
                                    City = "Aalborg",
                                    PostalCode = "9000",
                                    Street = "TestStreet 1"
                                });
                        });

                    b.OwnsOne("StoreManager.Domain.Common.ValueObjects.FullName", "StoreOwner", b1 =>
                        {
                            b1.Property<Guid>("StoreEntityId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("store_owner_first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("store_owner_last_name");

                            b1.HasKey("StoreEntityId");

                            b1.ToTable("store_entities");

                            b1.WithOwner()
                                .HasForeignKey("StoreEntityId")
                                .HasConstraintName("fk_store_entities_store_entities_id");

                            b1.HasData(
                                new
                                {
                                    StoreEntityId = new Guid("82d72abf-0045-4aaa-9d8b-78f28b437052"),
                                    FirstName = "John",
                                    LastName = "Doe"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("6c458b7e-c560-47c0-9e7c-5e66adf87192"),
                                    FirstName = "John",
                                    LastName = "Doe"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("d84a8b08-7d18-4c23-a8ac-efc11c585d74"),
                                    FirstName = "John",
                                    LastName = "Doe"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("7d7e8194-b981-478a-baee-57982fa3f699"),
                                    FirstName = "John",
                                    LastName = "Doe"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("2ecacee5-f3c8-43e0-9ca6-379c49248afb"),
                                    FirstName = "John",
                                    LastName = "Doe"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("2277a2ce-6623-4879-a3b5-709ba9fa625e"),
                                    FirstName = "John",
                                    LastName = "Doe"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("4a15bcc2-9104-46e7-8a6c-b2030c1d573b"),
                                    FirstName = "John",
                                    LastName = "Doe"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("23273be7-91ad-4095-a891-f10f0633a420"),
                                    FirstName = "John",
                                    LastName = "Doe"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("1e8d0a09-b7b9-4a94-a293-cff36e767bea"),
                                    FirstName = "John",
                                    LastName = "Doe"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("a2f309d9-e908-4ee1-9365-b72f7d088764"),
                                    FirstName = "John",
                                    LastName = "Doe"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("e0aa46d0-3e3f-43e3-beb0-d71dfbc8500a"),
                                    FirstName = "John",
                                    LastName = "Doe"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("ea911dd7-044d-45ff-b380-e04b5a8c1aa9"),
                                    FirstName = "John",
                                    LastName = "Doe"
                                });
                        });

                    b.OwnsOne("StoreManager.Domain.Common.ValueObjects.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("StoreEntityId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("id");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)")
                                .HasColumnName("phone_number_country_code");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(12)
                                .HasColumnType("nvarchar(12)")
                                .HasColumnName("phone_number_number");

                            b1.HasKey("StoreEntityId");

                            b1.ToTable("store_entities");

                            b1.WithOwner()
                                .HasForeignKey("StoreEntityId")
                                .HasConstraintName("fk_store_entities_store_entities_id");

                            b1.HasData(
                                new
                                {
                                    StoreEntityId = new Guid("82d72abf-0045-4aaa-9d8b-78f28b437052"),
                                    CountryCode = "+45",
                                    Number = "12345678"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("6c458b7e-c560-47c0-9e7c-5e66adf87192"),
                                    CountryCode = "+45",
                                    Number = "12345678"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("d84a8b08-7d18-4c23-a8ac-efc11c585d74"),
                                    CountryCode = "+45",
                                    Number = "12345678"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("7d7e8194-b981-478a-baee-57982fa3f699"),
                                    CountryCode = "+45",
                                    Number = "12345678"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("2ecacee5-f3c8-43e0-9ca6-379c49248afb"),
                                    CountryCode = "+45",
                                    Number = "12345678"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("2277a2ce-6623-4879-a3b5-709ba9fa625e"),
                                    CountryCode = "+45",
                                    Number = "12345678"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("4a15bcc2-9104-46e7-8a6c-b2030c1d573b"),
                                    CountryCode = "+45",
                                    Number = "12345678"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("23273be7-91ad-4095-a891-f10f0633a420"),
                                    CountryCode = "+45",
                                    Number = "12345678"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("1e8d0a09-b7b9-4a94-a293-cff36e767bea"),
                                    CountryCode = "+45",
                                    Number = "12345678"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("a2f309d9-e908-4ee1-9365-b72f7d088764"),
                                    CountryCode = "+45",
                                    Number = "12345678"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("e0aa46d0-3e3f-43e3-beb0-d71dfbc8500a"),
                                    CountryCode = "+45",
                                    Number = "12345678"
                                },
                                new
                                {
                                    StoreEntityId = new Guid("ea911dd7-044d-45ff-b380-e04b5a8c1aa9"),
                                    CountryCode = "+45",
                                    Number = "12345678"
                                });
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Chain");

                    b.Navigation("PhoneNumber")
                        .IsRequired();

                    b.Navigation("StoreOwner")
                        .IsRequired();
                });

            modelBuilder.Entity("StoreManager.Domain.Chain.ChainEntity", b =>
                {
                    b.Navigation("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
